parameters:
    darvin_menu.admin.form_type.menu.class: Darvin\MenuBundle\Form\Type\Admin\MenuType

    darvin_menu.admin.form_type.menu_item.class: Darvin\MenuBundle\Form\Type\Admin\MenuItemType

    darvin_menu.admin.form_type.menu_item_parent.class: Darvin\MenuBundle\Form\Type\Admin\MenuItemParentType

    darvin_menu.admin.form_type.slug_map_item.class: Darvin\MenuBundle\Form\Type\Admin\SlugMapItemType

    darvin_menu.admin.menu_item_factory.class: Darvin\MenuBundle\Admin\Menu\ItemFactory

    darvin_menu.admin.menu_item_sorter.class: Darvin\MenuBundle\Admin\Sorter\MenuItemSorter

    darvin_menu.admin.slug_map_item_link_view_widget.class: Darvin\MenuBundle\Admin\View\SlugMapItemLinkWidget

services:
    _defaults:
        public: true

    darvin_menu.admin.form_type.menu:
        class: '%darvin_menu.admin.form_type.menu.class%'
        arguments:
            - '@darvin_menu.configuration.menu'
            - '@darvin_admin.metadata.manager'
            - '@request_stack'
        tags:
            - { name: form.type }

    darvin_menu.admin.form_type.menu_item:
        class:  '%darvin_menu.admin.form_type.menu_item.class%'
        arguments:
            - '@darvin_utils.locale.provider'
        tags:
            - { name: form.type }

    darvin_menu.admin.form_type.menu_item_parent:
        class: '%darvin_menu.admin.form_type.menu_item_parent.class%'
        arguments:
            - '@darvin_utils.locale.provider'
            - '@darvin_menu.admin.menu_item_sorter'
            - '@darvin_menu.slug_map.object_loader'
        tags:
            - { name: form.type }

    darvin_menu.admin.form_type.slug_map_item:
        class: '%darvin_menu.admin.form_type.slug_map_item.class%'
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'
            - '@darvin_admin.entity_namer'
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_admin.metadata.manager'
            - '@property_accessor'
            - '@darvin_menu.slug_map.object_loader'
            - '@darvin_admin.metadata.sort_criteria_detector'
            - '@stof_doctrine_extensions.listener.tree'
            - '%darvin_menu.entities%'
        tags:
            - { name: form.type }

    darvin_menu.admin.menu_item_factory:
        class:  '%darvin_menu.admin.menu_item_factory.class%'
        public: false
        arguments:
            - '@darvin_admin.router'
            - '@security.authorization_checker'
            - '@darvin_menu.configuration.menu'
            - '@darvin_admin.metadata.manager'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_menu.admin.menu_item_sorter:
        class: '%darvin_menu.admin.menu_item_sorter.class%'
        arguments:
            - '@darvin_menu.slug_map.object_loader'
            - '@darvin_utils.tree.sorter'

    darvin_menu.admin.slug_map_item_link_view_widget:
        class:  '%darvin_menu.admin.slug_map_item_link_view_widget.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        arguments:
            - '@darvin_admin.entity_namer'
            - '@darvin_admin.view.widget.show_link'
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }
