parameters:
    darvin_menu.configuration.menu.class: Darvin\MenuBundle\Configuration\MenuConfiguration

services:
    darvin_menu.configuration.menu:
        class:  '%darvin_menu.configuration.menu.class%'
        public: true
        arguments:
            - '%darvin_menu.menus%'
