parameters:
    darvin_menu.configuration.menu.class: Darvin\MenuBundle\Configuration\MenuConfiguration

services:
    _defaults:
        public: true

    darvin_menu.configuration.menu:
        class: '%darvin_menu.configuration.menu.class%'
        arguments:
            - '%darvin_menu.menus%'
