parameters:
    darvin_menu.item_factory.abstract.class: Darvin\MenuBundle\Item\AbstractItemFactory

    darvin_menu.item_factory.slug_map.class:     Darvin\MenuBundle\Item\SlugMapItemFactory
    darvin_menu.item_factory.slug_map.uri_route: darvin_content_content_show

services:
    darvin_menu.item_factory.abstract:
        class:    "%darvin_menu.item_factory.abstract.class%"
        abstract: true
#        public:   false
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_menu.factory"

    darvin_menu.item_factory.slug_map:
        class:  "%darvin_menu.item_factory.slug_map.class%"
        parent: darvin_menu.item_factory.abstract
        arguments:
            - "@router"
            - "%darvin_menu.item_factory.slug_map.uri_route%"
