parameters:
    darvin_menu.repository.menu_item.class:  Darvin\MenuBundle\Repository\Menu\ItemRepository
    darvin_menu.repository.menu_item.entity: DarvinMenuBundle:Menu\Item

services:
    darvin_menu.repository.menu_item:
        class:   "%darvin_menu.repository.menu_item.class%"
        public:  false
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - "%darvin_menu.repository.menu_item.entity%"
