parameters:
    darvin_menu.slug_map.object_loader.class: Darvin\MenuBundle\Slug\SlugMapObjectLoader

services:
    _defaults:
        public: true

    darvin_menu.slug_map.object_loader:
        class:  '%darvin_menu.slug_map.object_loader.class%'
        public: false
        arguments:
            - '@darvin_utils.custom_object.loader'
            - '@darvin_image.orm.image_joiner'
            - '@darvin_utils.locale.provider'
            - '@darvin_content.translatable.translation_joiner'
