parameters:
    darvin_menu.knp.item.factory.abstract.class: Darvin\MenuBundle\Knp\Item\Factory\AbstractFactory

    darvin_menu.knp.item.factory.string.class: Darvin\MenuBundle\Knp\Item\Factory\StringFactory

    darvin_menu.knp.item.factory.entity.abstract.class: Darvin\MenuBundle\Knp\Item\Factory\Entity\AbstractEntityFactory

    darvin_menu.knp.item.factory.entity.menu_entry.class: Darvin\MenuBundle\Knp\Item\Factory\Entity\MenuEntryFactory

    darvin_menu.knp.item.factory.entity.slug_map_item.class: Darvin\MenuBundle\Knp\Item\Factory\Entity\SlugMapItemFactory

    darvin_menu.knp.item.factory_registry.class: Darvin\MenuBundle\Knp\Item\Factory\Registry\Registry

services:
    Darvin\MenuBundle\Knp\Item\Factory\Registry\KnpItemFactoryRegistryInterface: '@darvin_menu.knp.item.factory_registry'

    darvin_menu.knp.item.factory.abstract:
        class:    '%darvin_menu.knp.item.factory.abstract.class%'
        abstract: true
        calls:
            - [ setGenericItemFactory, [ '@knp_menu.factory' ] ]

    darvin_menu.knp.item.factory.string:
        class:  '%darvin_menu.knp.item.factory.string.class%'
        parent: darvin_menu.knp.item.factory.abstract
        tags:
            - { name: darvin_menu.knp.item.factory }

    darvin_menu.knp.item.factory.entity.abstract:
        class:    '%darvin_menu.knp.item.factory.entity.abstract.class%'
        parent:   darvin_menu.knp.item.factory.abstract
        abstract: true
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ setObjectNamer,   [ '@darvin_utils.object_namer' ] ]
            - [ setSlugMapRouter, [ '@darvin_content.router.slug_map' ] ]

    darvin_menu.knp.item.factory.entity.menu_entry:
        class:  '%darvin_menu.knp.item.factory.entity.menu_entry.class%'
        parent: darvin_menu.knp.item.factory.entity.abstract
        arguments:
            - '@request_stack'
        tags:
            - { name: darvin_menu.knp.item.factory }

    darvin_menu.knp.item.factory.entity.slug_map_item:
        class:  '%darvin_menu.knp.item.factory.entity.slug_map_item.class%'
        parent: darvin_menu.knp.item.factory.entity.abstract
        tags:
            - { name: darvin_menu.knp.item.factory }

    darvin_menu.knp.item.factory_registry:
        class: '%darvin_menu.knp.item.factory_registry.class%'
