parameters:
    darvin_menu.matcher.voter.uri.class: Darvin\MenuBundle\Matcher\Voter\UriVoter

services:
    darvin_menu.matcher.voter.uri:
        class: '%darvin_menu.matcher.voter.uri.class%'
        arguments:
            - '@request_stack'
        tags:
            - { name: knp_menu.voter }
