parameters:
    darvin_menu.fixture.menu_entry.class:     Darvin\MenuBundle\DataFixtures\ORM\Menu\LoadMenuEntryData
    darvin_menu.fixture.menu_entry.min_count: 10
    darvin_menu.fixture.menu_entry.max_count: 20
    darvin_menu.fixture.menu_entry.max_level: 3

services:
    darvin_menu.fixture.menu_entry:
        class: '%darvin_menu.fixture.menu_entry.class%'
        arguments:
            - '%darvin_menu.fixture.menu_entry.min_count%'
            - '%darvin_menu.fixture.menu_entry.max_count%'
            - '%darvin_menu.fixture.menu_entry.max_level%'
        tags:
            - { name: doctrine.fixture.orm, group: menu }
