menu:
    skip: true

pagination:
    enabled: false

searchable_fields:
    - title
    - url

sorter:
    id:     darvin_menu.admin.menu_item_sorter
    method: sort

joins:
    hover_image:   hoverImage
    image:         image
    slug_map_item: slugMapItem

order_by:
    menu:     asc
    level:    asc
    position: asc

view:
    index:
        fields:
            menuTitle:
                size:   sm
                widget: menu_title
            position:
                type: position
            enabled:
                type: checkbox
            showChildren:
                type: checkbox
            slugMapItem:
                size:   xxxl
                widget: slug_map_item_link
            image:
                size:   xxs
                widget: image_link
            hoverImage:
                size:   xxs
                widget: image_link
            title:
                size: xxl
            url:
                size:   free
                type:   link
                widget: simple_link
    extend~index~show:
        fields:
            remove~position:    ~
            remove~slugMapItem: ~

form:
    index:
        fields:
            position:
                type: Darvin\AdminBundle\Form\Type\PositionType
            enabled:      ~
            showChildren: ~
    filter:
        heading_field: menu
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            enabled:      ~
            showChildren: ~
            title:
                compare_strict: false
            url:
                compare_strict: false
    edit:
        type: Darvin\MenuBundle\Form\Type\Admin\MenuItemType
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
                options:
                    attr:
                        class: menu
            parent:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuItemParentType
            slugMapItem:
                type: Darvin\MenuBundle\Form\Type\Admin\SlugMapItemChoiceType
            showChildren:
                options:
                    required: false
            translations:
                type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                options:
                    label: false
                    fields:
                        enabled: ~
                        title:   ~
                        url:     ~
            image:
                type: Darvin\ImageBundle\Form\Type\ImageType
                options:
                    data_class: Darvin\MenuBundle\Entity\MenuItemImage
                    filters:    menu_main
            hoverImage:
                type: Darvin\ImageBundle\Form\Type\ImageType
                options:
                    data_class: Darvin\MenuBundle\Entity\MenuItemImage
                    filters:    menu_hover
