parameters:
    darvin_menu.item_manager.admin.base_form_type_extension.class: Darvin\MenuBundle\Form\Extension\Admin\ItemManagerBaseTypeExtension

    darvin_menu.item_manager.admin.form_type.class: Darvin\MenuBundle\Form\Type\Admin\MenuItemManagerType

    darvin_menu.item_manager.class: Darvin\MenuBundle\Item\MenuItemManager

services:
    darvin_menu.item_manager.admin.base_form_type_extension:
        class: "%darvin_menu.item_manager.admin.base_form_type_extension.class%"
        arguments:
            - "@darvin_menu.configuration.menu"
            - "@darvin_menu.item_manager"
        tags:
            - { name: form.type_extension, extended_type: Darvin\AdminBundle\Form\Type\BaseType }

    darvin_menu.item_manager.admin.form_type:
        class: "%darvin_menu.item_manager.admin.form_type.class%"
        arguments:
            - "@darvin_menu.configuration.menu"
        tags:
            - { name: form.type }

    darvin_menu.item_manager:
        class:  "%darvin_menu.item_manager.class%"
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
