darvin_admin:
    menu:
        groups:
            menu:
                position: 20
    sections:
        Darvin\MenuBundle\Entity\Menu\Item: '@DarvinMenuBundle/Resources/config/admin/menu/item.yaml'
