darvin_admin:
    menu:
        groups:
            menu:
                position: 20
    sections:
        Darvin\MenuBundle\Entity\MenuItem: '@DarvinMenuBundle/Resources/config/admin/menu_item.yaml'
