darvin_admin:
    menu:
        groups:
            menu:
                position: 20
    sections:
        Darvin\MenuBundle\Entity\MenuEntry: '@DarvinMenuBundle/Resources/config/admin/menu_entry.yaml'
