darvin_image:
    imagine:
        filter_sets:
            menu_hover:
                entities: Darvin\MenuBundle\Entity\Menu\MenuItemImage
                filters:
                    thumbnail: { size: [ 50, 50 ], mode: outbound }
            menu_main:
                entities: Darvin\MenuBundle\Entity\Menu\MenuItemImage
                filters:
                    thumbnail: { size: [ 50, 50 ], mode: outbound }
