parameters:
    darvin_menu.fixture.menu_item.class:     Darvin\MenuBundle\DataFixtures\ORM\Menu\LoadItemData
    darvin_menu.fixture.menu_item.min_count: 10
    darvin_menu.fixture.menu_item.max_count: 20
    darvin_menu.fixture.menu_item.max_level: 3

services:
    darvin_menu.fixture.menu_item:
        class: '%darvin_menu.fixture.menu_item.class%'
        arguments:
            - '%darvin_menu.fixture.menu_item.min_count%'
            - '%darvin_menu.fixture.menu_item.max_count%'
            - '%darvin_menu.fixture.menu_item.max_level%'
        tags:
            - { name: doctrine.fixture.orm, group: menu }
